# Generated by Django 3.0.2 on 2020-01-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='vidas',
            field=models.IntegerField(default=1, max_length=9999, verbose_name='Quantidade de vida'),
            preserve_default=False,
        ),
    ]
