# Generated by Django 3.0.2 on 2020-01-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_post_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria'},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
    ]
