# Generated by Django 3.0.2 on 2020-01-21 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20200120_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='my_app.Categoria', verbose_name='Categoria'),
            preserve_default=False,
        ),
    ]
